apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xray-ui-data
  annotations:
    nfs.io/storage-path: "config/xray-ui"
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
