apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: config
  namespace: shadowsocks
  labels:
    app: shadowsocks-rust
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: sops-secret-generator
behavior: create
disableNameSuffixHash: true
files:
  - config.json=config.enc.json
  - outbound-block-list.acl=outbound-block-list.enc.acl
