apiVersion: v1
kind: Service
metadata:
  name: resilio-sync
  namespace: resilio
spec:
  type: NodePort
  selector:
    app: resilio-sync
  ports:
    - port: 80
      targetPort: http-server
      nodePort: 30000
