apiVersion: v1
kind: PersistentVolume
metadata:
  name: resilio-sync
  namespace: resilio
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/mnt/disk1/resilio-sync"
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubuntu