apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-sync-claim
  namespace: resilio
spec:
  storageClassName: local-storage
  volumeName: resilio-sync
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G