apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
