apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-v2
  annotations:
    nfs.io/storage-path: "config/jackett"
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
