apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 7878
              name: http
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /movies
              name: movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-claim
        - name: movies
          persistentVolumeClaim:
            claimName: movies
