apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-v2
  annotations:
    nfs.io/storage-path: "config/radarr"
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
