apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 8989
              name: http
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /movies
              name: movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: movies
          persistentVolumeClaim:
            claimName: movies
