server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain:
        - "torrents.lavrov.nl"
        - "*.torrents.lavrov.nl"
      policy: bypass
    - domain:
        - "radarr.media.lavrov.nl"
      policy: one_factor
      subject:
        - 'group:non-trusted'
    - domain:
        - "lavrov.nl"
        - "*.lavrov.nl"
      policy: two_factor
      subject:
        - 'group:trusted'

session:
  name: authelia_session
  expiration: 24h
  inactivity: 1h
  remember_me: 1M
  cookies:
    - domain: 'lavrov.nl'
      authelia_url: 'https://auth.lavrov.nl'
      default_redirection_url: 'https://lavrov.nl'
      name: 'authelia_session'

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: false
  smtp:
    host: smtp.mail.svc.cluster.local
    port: 25
    sender: homelab@lavrov.nl
    disable_require_tls: true
