apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/mnt/disk1/movies"
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rpi0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-claim
spec:
  storageClassName: local-storage
  volumeName: movies
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
