apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  annotations:
    nfs.io/storage-path: "movies"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-nfs
  resources:
    requests:
      storage: 1T
