apiVersion: apps/v1
kind: Deployment
metadata:
  name: tubesync
spec:
  selector:
    matchLabels:
      app: tubesync
  replicas: 1
  template:
    metadata:
      labels:
        app: tubesync
    spec:
      containers:
        - name: tubesync
          image: ghcr.io/meeb/tubesync:latest
          ports:
            - containerPort: 4848
              name: http
          volumeMounts:
            - mountPath: /downloads
              name: movies
              subPath: videos
            - mountPath: /config
              name: config
      volumes:
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: config
          persistentVolumeClaim:
            claimName: tubesync-config
