apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: authelia-auth@kubernetescrd
spec:
  tls:
    - hosts:
      - "lavrov.nl"
      secretName: nginx-tls
  ingressClassName: traefik
  rules:
    - host: "lavrov.nl"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
