apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: torrentdam
spec:
  selector:
    matchLabels:
      app: indexer
  replicas: 1
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
        - name: indexer
          image: ghcr.io/torrentdam/indexer:7ba73c4a20fdaefbacb3eb6dc8d42eafe053ddb7
          resources:
            requests:
              memory: 200M
              cpu: 250m
            limits:
              memory: 300M
              cpu: 500m
          env:
            - name: NATS_SERVER
              value: nats://nats.torrentdam.svc.cluster.local:4222
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata
  namespace: torrentdam
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
