apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: torrentdam
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/torrentdam/server:9151e1ba4c8b6ecfde28ff03f94a63402bded707
          ports:
            - containerPort: 9999
              name: http
          resources:
            requests:
              memory: 200M
              cpu: 500m
            limits:
              memory: 500M
              cpu: 1
          livenessProbe:
            httpGet:
              path: "/"
              port: http
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: torrentdam
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: server-ws
  namespace: torrentdam
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  namespace: torrentdam
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: authelia-auth@kubernetescrd
    ingress.kubernetes.io/protocol: h2c
spec:
  tls:
    - hosts:
        - "server.torrents.home.lavrov.org"
      secretName: server-tls
  rules:
    - host: "server.torrents.home.lavrov.org"
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: server-ws
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 80
