apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: torrentdam
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/torrentdam/server:aa7e414fdcb23a66e8fabbef0a560ef1769eace5
          ports:
            - containerPort: 9999
          resources:
            requests:
              memory: 200M
              cpu: 250m
            limits:
              memory: 500M
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: torrentdam
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  namespace: torrentdam
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: authelia-auth@kubernetescrd
spec:
  tls:
    - hosts:
        - "server.torrents.home.lavrov.org"
      secretName: server-tls
  rules:
    - host: "server.torrents.home.lavrov.org"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 80
