apiVersion: v1
kind: Namespace
metadata:
  name: wireguard-public
  labels:
    name: wireguard-public
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-public-claim
  namespace: wireguard-public
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-public-configmap
  namespace: wireguard-public
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Amsterdam"
  SERVERURL: home.lavrov.org
  SERVERPORT: "31001"
  PEERS: "11"
  PEERDNS: "8.8.8.8"
  ALLOWEDIPS: "0.0.0.0/0"
---
apiVersion: v1
kind: Pod
metadata:
  name: wireguard-public
  namespace: wireguard-public
  labels:
    app: wireguard-public
spec:
  containers:
    - name: wireguard
      image: ghcr.io/linuxserver/wireguard
      envFrom:
        - configMapRef:
            name: wireguard-public-configmap
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
        privileged: true
      volumeMounts:
        - name: wg-config
          mountPath: /config
        - name: host-volumes
          mountPath: /lib/modules
      ports:
        - containerPort: 51820
          protocol: UDP
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
  volumes:
    - name: wg-config
      persistentVolumeClaim:
        claimName: wireguard-public-claim
    - name: host-volumes
      hostPath:
        path: /lib/modules
        type: Directory
  nodeSelector:
    "kubernetes.io/hostname": rpi0
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: wireguard-public
  name: wireguard-public
  namespace: wireguard-public
spec:
  type: NodePort
  ports:
    - port: 51820
      nodePort: 31001
      protocol: UDP
      targetPort: 51820
  selector:
    app: wireguard-public