apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-claim
  namespace: wireguard
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Amsterdam"
  SERVERURL: home.lavrov.org
  SERVERPORT: "31000"
  PEERS: "2"
  PEERDNS: "10.43.0.10, default.svc.cluster.local, svc.cluster.local"
  ALLOWEDIPS: "10.43.0.0/16, 10.42.0.0/16"  # k3s service and pod IPs
---
apiVersion: v1
kind: Pod
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app: wireguard
spec:
  containers:
    - name: wireguard
      image: ghcr.io/linuxserver/wireguard
      envFrom:
        - configMapRef:
            name: wireguard-configmap
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
        privileged: true
      volumeMounts:
        - name: wg-config
          mountPath: /config
        - name: host-volumes
          mountPath: /lib/modules
      ports:
        - containerPort: 51820
          protocol: UDP
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
  volumes:
    - name: wg-config
      persistentVolumeClaim:
        claimName: wireguard-claim
    - name: host-volumes
      hostPath:
        path: /lib/modules
        type: Directory
  nodeSelector:
    "kubernetes.io/hostname": rpi0
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: wireguard
  name: wireguard
  namespace: wireguard
spec:
  type: NodePort
  ports:
    - port: 51820
      nodePort: 31000
      protocol: UDP
      targetPort: 51820
  selector:
    app: wireguard