# Extends configuration generated by NixOS installer with homelab specific stuff

{ config, pkgs, ... }:

{
  imports = [
    ./services.nix
  ];

  # Support NFS filesystems.
  boot.supportedFilesystems = [ "nfs" ];

  users.users.vitaly = {
    isNormalUser = true;
    description = "Vitaly";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [];
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEA/WwH8LQYvNhN1jQ5wQmQ+cXZ1jTvyPPFeZCChd0+l5PB6HIk5N8aVtYatIL1heVde/96b+Kq571EAp0jPhfqlautM1+GxMsLsEa1nhRhYBNWuyEccQFv25NGhiEEWZJMQwIOg1LXyVOZ70FkAc96ftJuWV2L/TWsQhxHofAQGNtEGGn00z6RjGny4CblWReNmsEiPHHFsleCOGKu7palX8JNNdB3QKWrR+YY/Pon84469JQ/bqfCYNNzJL8wjkCGOqh+Fy9+iLe4wifjtjmiBfpZbOUUcWBHoeMMUrPD4jdD/x7TJdz1GHlWyGB2nFF103DkBHqUIxD0ZlTqYDh cardno:000615499727"
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDMHdIEI2GFee6/ZY2Df+3KPpQYVdqY3VUT/WSsfGKp/LxlpbGZVeNRhPcy+f65LMimNIuu5zqPgaCr/iifJbvYw2N6uO261461R6S4J3UGu+ijFAonDG3fy0QcIaeMXuA004ixadfhOPgM1tAKAA7e0QVlT2LWwODN8GhAaFIBkMYiVhf4t7R0Kt5G08oWtDyXM8x02+aQZXc3S1mVRiSxk9Q+x1bPt83nS1cLx7dwq/Af2ShVMG26T49YH5L23szR7F65ukdr6Qj89EF0QfTF7sfjSQ3EeZRyWvgSe5xduyTSd8M9Uqu0DqctKHwtLzqMbXMvJnTDKMX0ttBCVHX cardno:000615499738"
    ];
  };

  environment.systemPackages = with pkgs; [
    git
    vim
    curl
    htop-vim
  ];


  # Enable the OpenSSH daemon.
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.KbdInteractiveAuthentication = false;
  };
}
