apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: users
  namespace: authelia
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: sops-secret-generator
behavior: create
disableNameSuffixHash: true
files:
  - users_database.yml=config/users_database.enc.txt
