apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: users
  namespace: authelia
behavior: create
disableNameSuffixHash: true
files:
  - users_database.yml=config/users_database.enc.txt
