apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-users
  annotations:
    nfs.io/storage-path: "config/authelia/users"
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
  annotations:
    nfs.io/storage-path: "config/authelia/data"
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
