apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nats
  namespace: torrentdam
spec:
  repo: https://nats-io.github.io/k8s/helm/charts
  chart: nats
  version: "0.15.1"
  targetNamespace: torrentdam
  set:
    nats.jetstream.enabled: "true"
    reloader.image: "natsio/nats-server-config-reloader:0.6.2"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nack
  namespace: torrentdam
spec:
  repo: https://nats-io.github.io/k8s/helm/charts
  chart: nack
  version: "0.13.0"
  targetNamespace: torrentdam
  set:
    jetstream.nats.url: "nats://nats:4222"
