apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: torrents
spec:
  name: torrents
  subjects: ["discovered"]
  storage: file
  maxAge: 24h
---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: indexer
spec:
  streamName: torrents
  durableName: indexer
  filterSubject: discovered
  deliverPolicy: all
  ackPolicy: explicit