apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  replicas: 1
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:s6
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /svc
              name: downloads
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-claim
