apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  replicas: 1
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:s6
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /srv
              name: downloads
            - mountPath: /config
              name: config
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-claim
        - name: config
          configMap:
            name: config
            items:
              - key: settings.json
                path: settings.json
