apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-v2
  annotations:
    nfs.io/storage-path: "config/jellyfin"
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
