apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: postgres
  namespace: matrix
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: sops-secret-generator
type: Opaque
behavior: create
disableNameSuffixHash: true
envs:
  - passwords.enc.env
