apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: syncthing
  labels:
    app: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      volumes:
        - name: default
          persistentVolumeClaim:
            claimName: syncthing-claim
      containers:
        - name: syncthing
          image: syncthing/syncthing
          ports:
            - containerPort: 8384
              name: "http-server"
          volumeMounts:
            - name: default
              mountPath: /var/syncthing
