apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
spec:
  type: NodePort
  selector:
    app: syncthing
  ports:
    - name: http-server
      port: 80
      targetPort: http-server
      nodePort: 30001
