apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-claim
  namespace: syncthing
spec:
  storageClassName: local-storage
  volumeName: syncthing
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G