apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/torrentdam/cmd:latest
          args:
            - "dht"
            - "start"
            - "--port"
            - "6881"
          ports:
            - containerPort: 6881
              name: udp
          resources:
            requests:
              memory: 500M
              cpu: 1
            limits:
              memory: 500M
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: UDP
      port: 6881
      targetPort: 6881
---
apiVersion: v1
kind: Service
metadata:
  name: server-ext
spec:
  selector:
    app: server
  type: NodePort
  ports:
    - protocol: UDP
      nodePort: 32000
      port: 6881
